server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///E:/Desktop/msMelo/MS_Melodio/msconfigs/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
